/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BooleanFilterInput: { // input type
    and?: Array<boolean | null> | null; // [Boolean]
    between?: Array<boolean | null> | null; // [Boolean]
    contains?: boolean | null; // Boolean
    containsi?: boolean | null; // Boolean
    endsWith?: boolean | null; // Boolean
    eq?: boolean | null; // Boolean
    eqi?: boolean | null; // Boolean
    gt?: boolean | null; // Boolean
    gte?: boolean | null; // Boolean
    in?: Array<boolean | null> | null; // [Boolean]
    lt?: boolean | null; // Boolean
    lte?: boolean | null; // Boolean
    ne?: boolean | null; // Boolean
    nei?: boolean | null; // Boolean
    not?: NexusGenInputs['BooleanFilterInput'] | null; // BooleanFilterInput
    notContains?: boolean | null; // Boolean
    notContainsi?: boolean | null; // Boolean
    notIn?: Array<boolean | null> | null; // [Boolean]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<boolean | null> | null; // [Boolean]
    startsWith?: boolean | null; // Boolean
  }
  CartFiltersInput: { // input type
    and?: Array<NexusGenInputs['CartFiltersInput'] | null> | null; // [CartFiltersInput]
    cart_items?: NexusGenInputs['CartItemFiltersInput'] | null; // CartItemFiltersInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    not?: NexusGenInputs['CartFiltersInput'] | null; // CartFiltersInput
    or?: Array<NexusGenInputs['CartFiltersInput'] | null> | null; // [CartFiltersInput]
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  CartInput: { // input type
    cart_items?: Array<string | null> | null; // [ID]
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CartItemFiltersInput: { // input type
    and?: Array<NexusGenInputs['CartItemFiltersInput'] | null> | null; // [CartItemFiltersInput]
    cart?: NexusGenInputs['CartFiltersInput'] | null; // CartFiltersInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    not?: NexusGenInputs['CartItemFiltersInput'] | null; // CartItemFiltersInput
    or?: Array<NexusGenInputs['CartItemFiltersInput'] | null> | null; // [CartItemFiltersInput]
    product?: NexusGenInputs['ProductFiltersInput'] | null; // ProductFiltersInput
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    quantity?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  CartItemInput: { // input type
    cart?: string | null; // ID
    product?: string | null; // ID
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    quantity?: number | null; // Int
  }
  CategoryFiltersInput: { // input type
    and?: Array<NexusGenInputs['CategoryFiltersInput'] | null> | null; // [CategoryFiltersInput]
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    description?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['CategoryFiltersInput'] | null; // CategoryFiltersInput
    or?: Array<NexusGenInputs['CategoryFiltersInput'] | null> | null; // [CategoryFiltersInput]
    products?: NexusGenInputs['ProductFiltersInput'] | null; // ProductFiltersInput
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    slug?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  CategoryInput: { // input type
    description?: string | null; // String
    name?: string | null; // String
    products?: Array<string | null> | null; // [ID]
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    slug?: string | null; // String
  }
  CollectionFiltersInput: { // input type
    and?: Array<NexusGenInputs['CollectionFiltersInput'] | null> | null; // [CollectionFiltersInput]
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['CollectionFiltersInput'] | null; // CollectionFiltersInput
    or?: Array<NexusGenInputs['CollectionFiltersInput'] | null> | null; // [CollectionFiltersInput]
    products?: NexusGenInputs['ProductFiltersInput'] | null; // ProductFiltersInput
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  CollectionInput: { // input type
    name?: string | null; // String
    products?: Array<string | null> | null; // [ID]
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CommentFiltersInput: { // input type
    and?: Array<NexusGenInputs['CommentFiltersInput'] | null> | null; // [CommentFiltersInput]
    content?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    email?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    headline?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['CommentFiltersInput'] | null; // CommentFiltersInput
    or?: Array<NexusGenInputs['CommentFiltersInput'] | null> | null; // [CommentFiltersInput]
    product?: NexusGenInputs['ProductFiltersInput'] | null; // ProductFiltersInput
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    rating?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  CommentInput: { // input type
    content?: string | null; // String
    email?: string | null; // String
    headline?: string | null; // String
    name?: string | null; // String
    product?: string | null; // ID
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    rating?: number | null; // Int
  }
  DateFilterInput: { // input type
    and?: Array<NexusGenScalars['Date'] | null> | null; // [Date]
    between?: Array<NexusGenScalars['Date'] | null> | null; // [Date]
    contains?: NexusGenScalars['Date'] | null; // Date
    containsi?: NexusGenScalars['Date'] | null; // Date
    endsWith?: NexusGenScalars['Date'] | null; // Date
    eq?: NexusGenScalars['Date'] | null; // Date
    eqi?: NexusGenScalars['Date'] | null; // Date
    gt?: NexusGenScalars['Date'] | null; // Date
    gte?: NexusGenScalars['Date'] | null; // Date
    in?: Array<NexusGenScalars['Date'] | null> | null; // [Date]
    lt?: NexusGenScalars['Date'] | null; // Date
    lte?: NexusGenScalars['Date'] | null; // Date
    ne?: NexusGenScalars['Date'] | null; // Date
    nei?: NexusGenScalars['Date'] | null; // Date
    not?: NexusGenInputs['DateFilterInput'] | null; // DateFilterInput
    notContains?: NexusGenScalars['Date'] | null; // Date
    notContainsi?: NexusGenScalars['Date'] | null; // Date
    notIn?: Array<NexusGenScalars['Date'] | null> | null; // [Date]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<NexusGenScalars['Date'] | null> | null; // [Date]
    startsWith?: NexusGenScalars['Date'] | null; // Date
  }
  DateTimeFilterInput: { // input type
    and?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    between?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    contains?: NexusGenScalars['DateTime'] | null; // DateTime
    containsi?: NexusGenScalars['DateTime'] | null; // DateTime
    endsWith?: NexusGenScalars['DateTime'] | null; // DateTime
    eq?: NexusGenScalars['DateTime'] | null; // DateTime
    eqi?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    ne?: NexusGenScalars['DateTime'] | null; // DateTime
    nei?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    notContains?: NexusGenScalars['DateTime'] | null; // DateTime
    notContainsi?: NexusGenScalars['DateTime'] | null; // DateTime
    notIn?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    startsWith?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  FileInfoInput: { // input type
    alternativeText?: string | null; // String
    caption?: string | null; // String
    name?: string | null; // String
  }
  FloatFilterInput: { // input type
    and?: Array<number | null> | null; // [Float]
    between?: Array<number | null> | null; // [Float]
    contains?: number | null; // Float
    containsi?: number | null; // Float
    endsWith?: number | null; // Float
    eq?: number | null; // Float
    eqi?: number | null; // Float
    gt?: number | null; // Float
    gte?: number | null; // Float
    in?: Array<number | null> | null; // [Float]
    lt?: number | null; // Float
    lte?: number | null; // Float
    ne?: number | null; // Float
    nei?: number | null; // Float
    not?: NexusGenInputs['FloatFilterInput'] | null; // FloatFilterInput
    notContains?: number | null; // Float
    notContainsi?: number | null; // Float
    notIn?: Array<number | null> | null; // [Float]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<number | null> | null; // [Float]
    startsWith?: number | null; // Float
  }
  I18NLocaleFiltersInput: { // input type
    and?: Array<NexusGenInputs['I18NLocaleFiltersInput'] | null> | null; // [I18NLocaleFiltersInput]
    code?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['I18NLocaleFiltersInput'] | null; // I18NLocaleFiltersInput
    or?: Array<NexusGenInputs['I18NLocaleFiltersInput'] | null> | null; // [I18NLocaleFiltersInput]
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  I18NLocaleInput: { // input type
    code?: string | null; // String
    name?: string | null; // String
  }
  IDFilterInput: { // input type
    and?: Array<string | null> | null; // [ID]
    between?: Array<string | null> | null; // [ID]
    contains?: string | null; // ID
    containsi?: string | null; // ID
    endsWith?: string | null; // ID
    eq?: string | null; // ID
    eqi?: string | null; // ID
    gt?: string | null; // ID
    gte?: string | null; // ID
    in?: Array<string | null> | null; // [ID]
    lt?: string | null; // ID
    lte?: string | null; // ID
    ne?: string | null; // ID
    nei?: string | null; // ID
    not?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    notContains?: string | null; // ID
    notContainsi?: string | null; // ID
    notIn?: Array<string | null> | null; // [ID]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<string | null> | null; // [ID]
    startsWith?: string | null; // ID
  }
  IntFilterInput: { // input type
    and?: Array<number | null> | null; // [Int]
    between?: Array<number | null> | null; // [Int]
    contains?: number | null; // Int
    containsi?: number | null; // Int
    endsWith?: number | null; // Int
    eq?: number | null; // Int
    eqi?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: Array<number | null> | null; // [Int]
    lt?: number | null; // Int
    lte?: number | null; // Int
    ne?: number | null; // Int
    nei?: number | null; // Int
    not?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
    notContains?: number | null; // Int
    notContainsi?: number | null; // Int
    notIn?: Array<number | null> | null; // [Int]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<number | null> | null; // [Int]
    startsWith?: number | null; // Int
  }
  JSONFilterInput: { // input type
    and?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    between?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    contains?: NexusGenScalars['JSON'] | null; // JSON
    containsi?: NexusGenScalars['JSON'] | null; // JSON
    endsWith?: NexusGenScalars['JSON'] | null; // JSON
    eq?: NexusGenScalars['JSON'] | null; // JSON
    eqi?: NexusGenScalars['JSON'] | null; // JSON
    gt?: NexusGenScalars['JSON'] | null; // JSON
    gte?: NexusGenScalars['JSON'] | null; // JSON
    in?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    lt?: NexusGenScalars['JSON'] | null; // JSON
    lte?: NexusGenScalars['JSON'] | null; // JSON
    ne?: NexusGenScalars['JSON'] | null; // JSON
    nei?: NexusGenScalars['JSON'] | null; // JSON
    not?: NexusGenInputs['JSONFilterInput'] | null; // JSONFilterInput
    notContains?: NexusGenScalars['JSON'] | null; // JSON
    notContainsi?: NexusGenScalars['JSON'] | null; // JSON
    notIn?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<NexusGenScalars['JSON'] | null> | null; // [JSON]
    startsWith?: NexusGenScalars['JSON'] | null; // JSON
  }
  LongFilterInput: { // input type
    and?: Array<NexusGenScalars['Long'] | null> | null; // [Long]
    between?: Array<NexusGenScalars['Long'] | null> | null; // [Long]
    contains?: NexusGenScalars['Long'] | null; // Long
    containsi?: NexusGenScalars['Long'] | null; // Long
    endsWith?: NexusGenScalars['Long'] | null; // Long
    eq?: NexusGenScalars['Long'] | null; // Long
    eqi?: NexusGenScalars['Long'] | null; // Long
    gt?: NexusGenScalars['Long'] | null; // Long
    gte?: NexusGenScalars['Long'] | null; // Long
    in?: Array<NexusGenScalars['Long'] | null> | null; // [Long]
    lt?: NexusGenScalars['Long'] | null; // Long
    lte?: NexusGenScalars['Long'] | null; // Long
    ne?: NexusGenScalars['Long'] | null; // Long
    nei?: NexusGenScalars['Long'] | null; // Long
    not?: NexusGenInputs['LongFilterInput'] | null; // LongFilterInput
    notContains?: NexusGenScalars['Long'] | null; // Long
    notContainsi?: NexusGenScalars['Long'] | null; // Long
    notIn?: Array<NexusGenScalars['Long'] | null> | null; // [Long]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<NexusGenScalars['Long'] | null> | null; // [Long]
    startsWith?: NexusGenScalars['Long'] | null; // Long
  }
  PaginationArg: { // input type
    limit?: number | null; // Int
    page?: number | null; // Int
    pageSize?: number | null; // Int
    start?: number | null; // Int
  }
  ProductFiltersInput: { // input type
    and?: Array<NexusGenInputs['ProductFiltersInput'] | null> | null; // [ProductFiltersInput]
    avgRating?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
    cart_items?: NexusGenInputs['CartItemFiltersInput'] | null; // CartItemFiltersInput
    categories?: NexusGenInputs['CategoryFiltersInput'] | null; // CategoryFiltersInput
    collections?: NexusGenInputs['CollectionFiltersInput'] | null; // CollectionFiltersInput
    comments?: NexusGenInputs['CommentFiltersInput'] | null; // CommentFiltersInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    description?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['ProductFiltersInput'] | null; // ProductFiltersInput
    or?: Array<NexusGenInputs['ProductFiltersInput'] | null> | null; // [ProductFiltersInput]
    price?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
    publishedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    ratingCount?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
    slug?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  ProductInput: { // input type
    avgRating?: number | null; // Int
    cart_items?: Array<string | null> | null; // [ID]
    categories?: Array<string | null> | null; // [ID]
    collections?: Array<string | null> | null; // [ID]
    comments?: Array<string | null> | null; // [ID]
    description?: string | null; // String
    images?: Array<string | null> | null; // [ID]
    name?: string | null; // String
    price?: number | null; // Int
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    ratingCount?: number | null; // Int
    slug?: string | null; // String
  }
  StringFilterInput: { // input type
    and?: Array<string | null> | null; // [String]
    between?: Array<string | null> | null; // [String]
    contains?: string | null; // String
    containsi?: string | null; // String
    endsWith?: string | null; // String
    eq?: string | null; // String
    eqi?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    ne?: string | null; // String
    nei?: string | null; // String
    not?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    notContains?: string | null; // String
    notContainsi?: string | null; // String
    notIn?: Array<string | null> | null; // [String]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  TimeFilterInput: { // input type
    and?: Array<NexusGenScalars['Time'] | null> | null; // [Time]
    between?: Array<NexusGenScalars['Time'] | null> | null; // [Time]
    contains?: NexusGenScalars['Time'] | null; // Time
    containsi?: NexusGenScalars['Time'] | null; // Time
    endsWith?: NexusGenScalars['Time'] | null; // Time
    eq?: NexusGenScalars['Time'] | null; // Time
    eqi?: NexusGenScalars['Time'] | null; // Time
    gt?: NexusGenScalars['Time'] | null; // Time
    gte?: NexusGenScalars['Time'] | null; // Time
    in?: Array<NexusGenScalars['Time'] | null> | null; // [Time]
    lt?: NexusGenScalars['Time'] | null; // Time
    lte?: NexusGenScalars['Time'] | null; // Time
    ne?: NexusGenScalars['Time'] | null; // Time
    nei?: NexusGenScalars['Time'] | null; // Time
    not?: NexusGenInputs['TimeFilterInput'] | null; // TimeFilterInput
    notContains?: NexusGenScalars['Time'] | null; // Time
    notContainsi?: NexusGenScalars['Time'] | null; // Time
    notIn?: Array<NexusGenScalars['Time'] | null> | null; // [Time]
    notNull?: boolean | null; // Boolean
    null?: boolean | null; // Boolean
    or?: Array<NexusGenScalars['Time'] | null> | null; // [Time]
    startsWith?: NexusGenScalars['Time'] | null; // Time
  }
  UploadFileFiltersInput: { // input type
    alternativeText?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    and?: Array<NexusGenInputs['UploadFileFiltersInput'] | null> | null; // [UploadFileFiltersInput]
    caption?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    ext?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    folder?: NexusGenInputs['UploadFolderFiltersInput'] | null; // UploadFolderFiltersInput
    folderPath?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    formats?: NexusGenInputs['JSONFilterInput'] | null; // JSONFilterInput
    hash?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    height?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    mime?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['UploadFileFiltersInput'] | null; // UploadFileFiltersInput
    or?: Array<NexusGenInputs['UploadFileFiltersInput'] | null> | null; // [UploadFileFiltersInput]
    previewUrl?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    provider?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    provider_metadata?: NexusGenInputs['JSONFilterInput'] | null; // JSONFilterInput
    size?: NexusGenInputs['FloatFilterInput'] | null; // FloatFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    url?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    width?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
  }
  UploadFileInput: { // input type
    alternativeText?: string | null; // String
    caption?: string | null; // String
    ext?: string | null; // String
    folder?: string | null; // ID
    folderPath?: string | null; // String
    formats?: NexusGenScalars['JSON'] | null; // JSON
    hash?: string | null; // String
    height?: number | null; // Int
    mime?: string | null; // String
    name?: string | null; // String
    previewUrl?: string | null; // String
    provider?: string | null; // String
    provider_metadata?: NexusGenScalars['JSON'] | null; // JSON
    size?: number | null; // Float
    url?: string | null; // String
    width?: number | null; // Int
  }
  UploadFolderFiltersInput: { // input type
    and?: Array<NexusGenInputs['UploadFolderFiltersInput'] | null> | null; // [UploadFolderFiltersInput]
    children?: NexusGenInputs['UploadFolderFiltersInput'] | null; // UploadFolderFiltersInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    files?: NexusGenInputs['UploadFileFiltersInput'] | null; // UploadFileFiltersInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['UploadFolderFiltersInput'] | null; // UploadFolderFiltersInput
    or?: Array<NexusGenInputs['UploadFolderFiltersInput'] | null> | null; // [UploadFolderFiltersInput]
    parent?: NexusGenInputs['UploadFolderFiltersInput'] | null; // UploadFolderFiltersInput
    path?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    pathId?: NexusGenInputs['IntFilterInput'] | null; // IntFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  UploadFolderInput: { // input type
    children?: Array<string | null> | null; // [ID]
    files?: Array<string | null> | null; // [ID]
    name?: string | null; // String
    parent?: string | null; // ID
    path?: string | null; // String
    pathId?: number | null; // Int
  }
  UsersPermissionsLoginInput: { // input type
    identifier: string; // String!
    password: string; // String!
    provider: string; // String!
  }
  UsersPermissionsPermissionFiltersInput: { // input type
    action?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    and?: Array<NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null> | null; // [UsersPermissionsPermissionFiltersInput]
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    not?: NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null; // UsersPermissionsPermissionFiltersInput
    or?: Array<NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null> | null; // [UsersPermissionsPermissionFiltersInput]
    role?: NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null; // UsersPermissionsRoleFiltersInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
  }
  UsersPermissionsPermissionInput: { // input type
    action?: string | null; // String
    role?: string | null; // ID
  }
  UsersPermissionsRegisterInput: { // input type
    email: string; // String!
    password: string; // String!
    username: string; // String!
  }
  UsersPermissionsRoleFiltersInput: { // input type
    and?: Array<NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null> | null; // [UsersPermissionsRoleFiltersInput]
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    description?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    name?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    not?: NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null; // UsersPermissionsRoleFiltersInput
    or?: Array<NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null> | null; // [UsersPermissionsRoleFiltersInput]
    permissions?: NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null; // UsersPermissionsPermissionFiltersInput
    type?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    users?: NexusGenInputs['UsersPermissionsUserFiltersInput'] | null; // UsersPermissionsUserFiltersInput
  }
  UsersPermissionsRoleInput: { // input type
    description?: string | null; // String
    name?: string | null; // String
    permissions?: Array<string | null> | null; // [ID]
    type?: string | null; // String
    users?: Array<string | null> | null; // [ID]
  }
  UsersPermissionsUserFiltersInput: { // input type
    and?: Array<NexusGenInputs['UsersPermissionsUserFiltersInput'] | null> | null; // [UsersPermissionsUserFiltersInput]
    blocked?: NexusGenInputs['BooleanFilterInput'] | null; // BooleanFilterInput
    confirmationToken?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    confirmed?: NexusGenInputs['BooleanFilterInput'] | null; // BooleanFilterInput
    createdAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    email?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    id?: NexusGenInputs['IDFilterInput'] | null; // IDFilterInput
    not?: NexusGenInputs['UsersPermissionsUserFiltersInput'] | null; // UsersPermissionsUserFiltersInput
    or?: Array<NexusGenInputs['UsersPermissionsUserFiltersInput'] | null> | null; // [UsersPermissionsUserFiltersInput]
    password?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    provider?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    resetPasswordToken?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
    role?: NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null; // UsersPermissionsRoleFiltersInput
    updatedAt?: NexusGenInputs['DateTimeFilterInput'] | null; // DateTimeFilterInput
    username?: NexusGenInputs['StringFilterInput'] | null; // StringFilterInput
  }
  UsersPermissionsUserInput: { // input type
    blocked?: boolean | null; // Boolean
    confirmationToken?: string | null; // String
    confirmed?: boolean | null; // Boolean
    email?: string | null; // String
    password?: string | null; // String
    provider?: string | null; // String
    resetPasswordToken?: string | null; // String
    role?: string | null; // ID
    username?: string | null; // String
  }
}

export interface NexusGenEnums {
  PublicationState: "live" | "preview"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Date: any
  DateTime: any
  I18NLocaleCode: any
  JSON: any
  Long: any
  Time: any
  Upload: any
}

export interface NexusGenObjects {
  Cart: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CartEntity: {};
  CartEntityResponse: {};
  CartEntityResponseCollection: {};
  CartItem: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    quantity?: number | null; // Int
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CartItemEntity: {};
  CartItemEntityResponse: {};
  CartItemEntityResponseCollection: {};
  CartItemRelationResponseCollection: {};
  CartRelationResponseCollection: {};
  Category: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description: string; // String!
    name: string; // String!
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    slug?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoryEntity: {};
  CategoryEntityResponse: {};
  CategoryEntityResponseCollection: {};
  CategoryRelationResponseCollection: {};
  Collection: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    name: string; // String!
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CollectionEntity: {};
  CollectionEntityResponse: {};
  CollectionEntityResponseCollection: {};
  CollectionRelationResponseCollection: {};
  Comment: { // root type
    content: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    headline: string; // String!
    name: string; // String!
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    rating: number; // Int!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CommentEntity: {};
  CommentEntityResponse: {};
  CommentEntityResponseCollection: {};
  CommentRelationResponseCollection: {};
  Error: { // root type
    message?: string | null; // String
  }
  I18NLocale: { // root type
    code?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    name?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  I18NLocaleEntity: {};
  I18NLocaleEntityResponse: {};
  I18NLocaleEntityResponseCollection: {};
  I18NLocaleRelationResponseCollection: {};
  Mutation: {};
  Pagination: { // root type
    page: number; // Int!
    pageCount: number; // Int!
    pageSize: number; // Int!
    total: number; // Int!
  }
  Product: { // root type
    avgRating?: number | null; // Int
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description: string; // String!
    name: string; // String!
    price: number; // Int!
    publishedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    ratingCount?: number | null; // Int
    slug: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ProductEntity: {};
  ProductEntityResponse: {};
  ProductEntityResponseCollection: {};
  ProductRelationResponseCollection: {};
  Query: {};
  ResponseCollectionMeta: {};
  UploadFile: { // root type
    alternativeText?: string | null; // String
    caption?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    ext?: string | null; // String
    formats?: NexusGenScalars['JSON'] | null; // JSON
    hash: string; // String!
    height?: number | null; // Int
    mime: string; // String!
    name: string; // String!
    previewUrl?: string | null; // String
    provider: string; // String!
    provider_metadata?: NexusGenScalars['JSON'] | null; // JSON
    size: number; // Float!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    url: string; // String!
    width?: number | null; // Int
  }
  UploadFileEntity: {};
  UploadFileEntityResponse: {};
  UploadFileEntityResponseCollection: {};
  UploadFileRelationResponseCollection: {};
  UploadFolder: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    name: string; // String!
    path: string; // String!
    pathId: number; // Int!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UploadFolderEntity: {};
  UploadFolderEntityResponse: {};
  UploadFolderEntityResponseCollection: {};
  UploadFolderRelationResponseCollection: {};
  UsersPermissionsCreateRolePayload: { // root type
    ok: boolean; // Boolean!
  }
  UsersPermissionsDeleteRolePayload: { // root type
    ok: boolean; // Boolean!
  }
  UsersPermissionsLoginPayload: { // root type
    jwt?: string | null; // String
    user: NexusGenRootTypes['UsersPermissionsMe']; // UsersPermissionsMe!
  }
  UsersPermissionsMe: { // root type
    blocked?: boolean | null; // Boolean
    confirmed?: boolean | null; // Boolean
    email?: string | null; // String
    id: string; // ID!
    role?: NexusGenRootTypes['UsersPermissionsMeRole'] | null; // UsersPermissionsMeRole
    username: string; // String!
  }
  UsersPermissionsMeRole: { // root type
    description?: string | null; // String
    id: string; // ID!
    name: string; // String!
    type?: string | null; // String
  }
  UsersPermissionsPasswordPayload: { // root type
    ok: boolean; // Boolean!
  }
  UsersPermissionsPermission: { // root type
    action: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UsersPermissionsPermissionEntity: {};
  UsersPermissionsPermissionEntityResponse: {};
  UsersPermissionsPermissionEntityResponseCollection: {};
  UsersPermissionsPermissionRelationResponseCollection: {};
  UsersPermissionsRole: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    name: string; // String!
    type?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UsersPermissionsRoleEntity: {};
  UsersPermissionsRoleEntityResponse: {};
  UsersPermissionsRoleEntityResponseCollection: {};
  UsersPermissionsRoleRelationResponseCollection: {};
  UsersPermissionsUpdateRolePayload: { // root type
    ok: boolean; // Boolean!
  }
  UsersPermissionsUser: { // root type
    blocked?: boolean | null; // Boolean
    confirmed?: boolean | null; // Boolean
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    provider?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    username: string; // String!
  }
  UsersPermissionsUserEntity: {};
  UsersPermissionsUserEntityResponse: {};
  UsersPermissionsUserEntityResponseCollection: {};
  UsersPermissionsUserRelationResponseCollection: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
  GenericMorph: NexusGenRootTypes['Cart'] | NexusGenRootTypes['CartItem'] | NexusGenRootTypes['Category'] | NexusGenRootTypes['Collection'] | NexusGenRootTypes['Comment'] | NexusGenRootTypes['I18NLocale'] | NexusGenRootTypes['Product'] | NexusGenRootTypes['UploadFile'] | NexusGenRootTypes['UploadFolder'] | NexusGenRootTypes['UsersPermissionsPermission'] | NexusGenRootTypes['UsersPermissionsRole'] | NexusGenRootTypes['UsersPermissionsUser'];
}

export type NexusGenRootTypes = NexusGenObjects & NexusGenUnions

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Cart: { // field return type
    cart_items: NexusGenRootTypes['CartItemRelationResponseCollection'] | null; // CartItemRelationResponseCollection
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CartEntity: { // field return type
    attributes: NexusGenRootTypes['Cart'] | null; // Cart
    id: string | null; // ID
  }
  CartEntityResponse: { // field return type
    data: NexusGenRootTypes['CartEntity'] | null; // CartEntity
  }
  CartEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['CartEntity'][]; // [CartEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  CartItem: { // field return type
    cart: NexusGenRootTypes['CartEntityResponse'] | null; // CartEntityResponse
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    product: NexusGenRootTypes['ProductEntityResponse'] | null; // ProductEntityResponse
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    quantity: number | null; // Int
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CartItemEntity: { // field return type
    attributes: NexusGenRootTypes['CartItem'] | null; // CartItem
    id: string | null; // ID
  }
  CartItemEntityResponse: { // field return type
    data: NexusGenRootTypes['CartItemEntity'] | null; // CartItemEntity
  }
  CartItemEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['CartItemEntity'][]; // [CartItemEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  CartItemRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['CartItemEntity'][]; // [CartItemEntity!]!
  }
  CartRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['CartEntity'][]; // [CartEntity!]!
  }
  Category: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    description: string; // String!
    name: string; // String!
    products: NexusGenRootTypes['ProductRelationResponseCollection'] | null; // ProductRelationResponseCollection
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    slug: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoryEntity: { // field return type
    attributes: NexusGenRootTypes['Category'] | null; // Category
    id: string | null; // ID
  }
  CategoryEntityResponse: { // field return type
    data: NexusGenRootTypes['CategoryEntity'] | null; // CategoryEntity
  }
  CategoryEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['CategoryEntity'][]; // [CategoryEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  CategoryRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['CategoryEntity'][]; // [CategoryEntity!]!
  }
  Collection: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    name: string; // String!
    products: NexusGenRootTypes['ProductRelationResponseCollection'] | null; // ProductRelationResponseCollection
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CollectionEntity: { // field return type
    attributes: NexusGenRootTypes['Collection'] | null; // Collection
    id: string | null; // ID
  }
  CollectionEntityResponse: { // field return type
    data: NexusGenRootTypes['CollectionEntity'] | null; // CollectionEntity
  }
  CollectionEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['CollectionEntity'][]; // [CollectionEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  CollectionRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['CollectionEntity'][]; // [CollectionEntity!]!
  }
  Comment: { // field return type
    content: string; // String!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    headline: string; // String!
    name: string; // String!
    product: NexusGenRootTypes['ProductEntityResponse'] | null; // ProductEntityResponse
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    rating: number; // Int!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CommentEntity: { // field return type
    attributes: NexusGenRootTypes['Comment'] | null; // Comment
    id: string | null; // ID
  }
  CommentEntityResponse: { // field return type
    data: NexusGenRootTypes['CommentEntity'] | null; // CommentEntity
  }
  CommentEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['CommentEntity'][]; // [CommentEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  CommentRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['CommentEntity'][]; // [CommentEntity!]!
  }
  Error: { // field return type
    code: string; // String!
    message: string | null; // String
  }
  I18NLocale: { // field return type
    code: string | null; // String
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    name: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  I18NLocaleEntity: { // field return type
    attributes: NexusGenRootTypes['I18NLocale'] | null; // I18NLocale
    id: string | null; // ID
  }
  I18NLocaleEntityResponse: { // field return type
    data: NexusGenRootTypes['I18NLocaleEntity'] | null; // I18NLocaleEntity
  }
  I18NLocaleEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['I18NLocaleEntity'][]; // [I18NLocaleEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  I18NLocaleRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['I18NLocaleEntity'][]; // [I18NLocaleEntity!]!
  }
  Mutation: { // field return type
    changePassword: NexusGenRootTypes['UsersPermissionsLoginPayload'] | null; // UsersPermissionsLoginPayload
    createCart: NexusGenRootTypes['CartEntityResponse'] | null; // CartEntityResponse
    createCartItem: NexusGenRootTypes['CartItemEntityResponse'] | null; // CartItemEntityResponse
    createCategory: NexusGenRootTypes['CategoryEntityResponse'] | null; // CategoryEntityResponse
    createCollection: NexusGenRootTypes['CollectionEntityResponse'] | null; // CollectionEntityResponse
    createComment: NexusGenRootTypes['CommentEntityResponse'] | null; // CommentEntityResponse
    createProduct: NexusGenRootTypes['ProductEntityResponse'] | null; // ProductEntityResponse
    createUploadFile: NexusGenRootTypes['UploadFileEntityResponse'] | null; // UploadFileEntityResponse
    createUploadFolder: NexusGenRootTypes['UploadFolderEntityResponse'] | null; // UploadFolderEntityResponse
    createUsersPermissionsRole: NexusGenRootTypes['UsersPermissionsCreateRolePayload'] | null; // UsersPermissionsCreateRolePayload
    createUsersPermissionsUser: NexusGenRootTypes['UsersPermissionsUserEntityResponse']; // UsersPermissionsUserEntityResponse!
    deleteCart: NexusGenRootTypes['CartEntityResponse'] | null; // CartEntityResponse
    deleteCartItem: NexusGenRootTypes['CartItemEntityResponse'] | null; // CartItemEntityResponse
    deleteCategory: NexusGenRootTypes['CategoryEntityResponse'] | null; // CategoryEntityResponse
    deleteCollection: NexusGenRootTypes['CollectionEntityResponse'] | null; // CollectionEntityResponse
    deleteComment: NexusGenRootTypes['CommentEntityResponse'] | null; // CommentEntityResponse
    deleteProduct: NexusGenRootTypes['ProductEntityResponse'] | null; // ProductEntityResponse
    deleteUploadFile: NexusGenRootTypes['UploadFileEntityResponse'] | null; // UploadFileEntityResponse
    deleteUploadFolder: NexusGenRootTypes['UploadFolderEntityResponse'] | null; // UploadFolderEntityResponse
    deleteUsersPermissionsRole: NexusGenRootTypes['UsersPermissionsDeleteRolePayload'] | null; // UsersPermissionsDeleteRolePayload
    deleteUsersPermissionsUser: NexusGenRootTypes['UsersPermissionsUserEntityResponse']; // UsersPermissionsUserEntityResponse!
    emailConfirmation: NexusGenRootTypes['UsersPermissionsLoginPayload'] | null; // UsersPermissionsLoginPayload
    forgotPassword: NexusGenRootTypes['UsersPermissionsPasswordPayload'] | null; // UsersPermissionsPasswordPayload
    login: NexusGenRootTypes['UsersPermissionsLoginPayload']; // UsersPermissionsLoginPayload!
    multipleUpload: Array<NexusGenRootTypes['UploadFileEntityResponse'] | null>; // [UploadFileEntityResponse]!
    register: NexusGenRootTypes['UsersPermissionsLoginPayload']; // UsersPermissionsLoginPayload!
    removeFile: NexusGenRootTypes['UploadFileEntityResponse'] | null; // UploadFileEntityResponse
    resetPassword: NexusGenRootTypes['UsersPermissionsLoginPayload'] | null; // UsersPermissionsLoginPayload
    updateCart: NexusGenRootTypes['CartEntityResponse'] | null; // CartEntityResponse
    updateCartItem: NexusGenRootTypes['CartItemEntityResponse'] | null; // CartItemEntityResponse
    updateCategory: NexusGenRootTypes['CategoryEntityResponse'] | null; // CategoryEntityResponse
    updateCollection: NexusGenRootTypes['CollectionEntityResponse'] | null; // CollectionEntityResponse
    updateComment: NexusGenRootTypes['CommentEntityResponse'] | null; // CommentEntityResponse
    updateFileInfo: NexusGenRootTypes['UploadFileEntityResponse']; // UploadFileEntityResponse!
    updateProduct: NexusGenRootTypes['ProductEntityResponse'] | null; // ProductEntityResponse
    updateUploadFile: NexusGenRootTypes['UploadFileEntityResponse'] | null; // UploadFileEntityResponse
    updateUploadFolder: NexusGenRootTypes['UploadFolderEntityResponse'] | null; // UploadFolderEntityResponse
    updateUsersPermissionsRole: NexusGenRootTypes['UsersPermissionsUpdateRolePayload'] | null; // UsersPermissionsUpdateRolePayload
    updateUsersPermissionsUser: NexusGenRootTypes['UsersPermissionsUserEntityResponse']; // UsersPermissionsUserEntityResponse!
    upload: NexusGenRootTypes['UploadFileEntityResponse']; // UploadFileEntityResponse!
  }
  Pagination: { // field return type
    page: number; // Int!
    pageCount: number; // Int!
    pageSize: number; // Int!
    total: number; // Int!
  }
  Product: { // field return type
    avgRating: number | null; // Int
    cart_items: NexusGenRootTypes['CartItemRelationResponseCollection'] | null; // CartItemRelationResponseCollection
    categories: NexusGenRootTypes['CategoryRelationResponseCollection'] | null; // CategoryRelationResponseCollection
    collections: NexusGenRootTypes['CollectionRelationResponseCollection'] | null; // CollectionRelationResponseCollection
    comments: NexusGenRootTypes['CommentRelationResponseCollection'] | null; // CommentRelationResponseCollection
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    description: string; // String!
    images: NexusGenRootTypes['UploadFileRelationResponseCollection']; // UploadFileRelationResponseCollection!
    name: string; // String!
    price: number; // Int!
    publishedAt: NexusGenScalars['DateTime'] | null; // DateTime
    ratingCount: number | null; // Int
    slug: string; // String!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ProductEntity: { // field return type
    attributes: NexusGenRootTypes['Product'] | null; // Product
    id: string | null; // ID
  }
  ProductEntityResponse: { // field return type
    data: NexusGenRootTypes['ProductEntity'] | null; // ProductEntity
  }
  ProductEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['ProductEntity'][]; // [ProductEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  ProductRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['ProductEntity'][]; // [ProductEntity!]!
  }
  Query: { // field return type
    cart: NexusGenRootTypes['CartEntityResponse'] | null; // CartEntityResponse
    cartItem: NexusGenRootTypes['CartItemEntityResponse'] | null; // CartItemEntityResponse
    cartItems: NexusGenRootTypes['CartItemEntityResponseCollection'] | null; // CartItemEntityResponseCollection
    carts: NexusGenRootTypes['CartEntityResponseCollection'] | null; // CartEntityResponseCollection
    categories: NexusGenRootTypes['CategoryEntityResponseCollection'] | null; // CategoryEntityResponseCollection
    category: NexusGenRootTypes['CategoryEntityResponse'] | null; // CategoryEntityResponse
    collection: NexusGenRootTypes['CollectionEntityResponse'] | null; // CollectionEntityResponse
    collections: NexusGenRootTypes['CollectionEntityResponseCollection'] | null; // CollectionEntityResponseCollection
    comment: NexusGenRootTypes['CommentEntityResponse'] | null; // CommentEntityResponse
    comments: NexusGenRootTypes['CommentEntityResponseCollection'] | null; // CommentEntityResponseCollection
    i18NLocale: NexusGenRootTypes['I18NLocaleEntityResponse'] | null; // I18NLocaleEntityResponse
    i18NLocales: NexusGenRootTypes['I18NLocaleEntityResponseCollection'] | null; // I18NLocaleEntityResponseCollection
    me: NexusGenRootTypes['UsersPermissionsMe'] | null; // UsersPermissionsMe
    product: NexusGenRootTypes['ProductEntityResponse'] | null; // ProductEntityResponse
    products: NexusGenRootTypes['ProductEntityResponseCollection'] | null; // ProductEntityResponseCollection
    uploadFile: NexusGenRootTypes['UploadFileEntityResponse'] | null; // UploadFileEntityResponse
    uploadFiles: NexusGenRootTypes['UploadFileEntityResponseCollection'] | null; // UploadFileEntityResponseCollection
    uploadFolder: NexusGenRootTypes['UploadFolderEntityResponse'] | null; // UploadFolderEntityResponse
    uploadFolders: NexusGenRootTypes['UploadFolderEntityResponseCollection'] | null; // UploadFolderEntityResponseCollection
    usersPermissionsRole: NexusGenRootTypes['UsersPermissionsRoleEntityResponse'] | null; // UsersPermissionsRoleEntityResponse
    usersPermissionsRoles: NexusGenRootTypes['UsersPermissionsRoleEntityResponseCollection'] | null; // UsersPermissionsRoleEntityResponseCollection
    usersPermissionsUser: NexusGenRootTypes['UsersPermissionsUserEntityResponse'] | null; // UsersPermissionsUserEntityResponse
    usersPermissionsUsers: NexusGenRootTypes['UsersPermissionsUserEntityResponseCollection'] | null; // UsersPermissionsUserEntityResponseCollection
  }
  ResponseCollectionMeta: { // field return type
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  UploadFile: { // field return type
    alternativeText: string | null; // String
    caption: string | null; // String
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    ext: string | null; // String
    formats: NexusGenScalars['JSON'] | null; // JSON
    hash: string; // String!
    height: number | null; // Int
    mime: string; // String!
    name: string; // String!
    previewUrl: string | null; // String
    provider: string; // String!
    provider_metadata: NexusGenScalars['JSON'] | null; // JSON
    related: Array<NexusGenRootTypes['GenericMorph'] | null> | null; // [GenericMorph]
    size: number; // Float!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    url: string; // String!
    width: number | null; // Int
  }
  UploadFileEntity: { // field return type
    attributes: NexusGenRootTypes['UploadFile'] | null; // UploadFile
    id: string | null; // ID
  }
  UploadFileEntityResponse: { // field return type
    data: NexusGenRootTypes['UploadFileEntity'] | null; // UploadFileEntity
  }
  UploadFileEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['UploadFileEntity'][]; // [UploadFileEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  UploadFileRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['UploadFileEntity'][]; // [UploadFileEntity!]!
  }
  UploadFolder: { // field return type
    children: NexusGenRootTypes['UploadFolderRelationResponseCollection'] | null; // UploadFolderRelationResponseCollection
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    files: NexusGenRootTypes['UploadFileRelationResponseCollection'] | null; // UploadFileRelationResponseCollection
    name: string; // String!
    parent: NexusGenRootTypes['UploadFolderEntityResponse'] | null; // UploadFolderEntityResponse
    path: string; // String!
    pathId: number; // Int!
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UploadFolderEntity: { // field return type
    attributes: NexusGenRootTypes['UploadFolder'] | null; // UploadFolder
    id: string | null; // ID
  }
  UploadFolderEntityResponse: { // field return type
    data: NexusGenRootTypes['UploadFolderEntity'] | null; // UploadFolderEntity
  }
  UploadFolderEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['UploadFolderEntity'][]; // [UploadFolderEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  UploadFolderRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['UploadFolderEntity'][]; // [UploadFolderEntity!]!
  }
  UsersPermissionsCreateRolePayload: { // field return type
    ok: boolean; // Boolean!
  }
  UsersPermissionsDeleteRolePayload: { // field return type
    ok: boolean; // Boolean!
  }
  UsersPermissionsLoginPayload: { // field return type
    jwt: string | null; // String
    user: NexusGenRootTypes['UsersPermissionsMe']; // UsersPermissionsMe!
  }
  UsersPermissionsMe: { // field return type
    blocked: boolean | null; // Boolean
    confirmed: boolean | null; // Boolean
    email: string | null; // String
    id: string; // ID!
    role: NexusGenRootTypes['UsersPermissionsMeRole'] | null; // UsersPermissionsMeRole
    username: string; // String!
  }
  UsersPermissionsMeRole: { // field return type
    description: string | null; // String
    id: string; // ID!
    name: string; // String!
    type: string | null; // String
  }
  UsersPermissionsPasswordPayload: { // field return type
    ok: boolean; // Boolean!
  }
  UsersPermissionsPermission: { // field return type
    action: string; // String!
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    role: NexusGenRootTypes['UsersPermissionsRoleEntityResponse'] | null; // UsersPermissionsRoleEntityResponse
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UsersPermissionsPermissionEntity: { // field return type
    attributes: NexusGenRootTypes['UsersPermissionsPermission'] | null; // UsersPermissionsPermission
    id: string | null; // ID
  }
  UsersPermissionsPermissionEntityResponse: { // field return type
    data: NexusGenRootTypes['UsersPermissionsPermissionEntity'] | null; // UsersPermissionsPermissionEntity
  }
  UsersPermissionsPermissionEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['UsersPermissionsPermissionEntity'][]; // [UsersPermissionsPermissionEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  UsersPermissionsPermissionRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['UsersPermissionsPermissionEntity'][]; // [UsersPermissionsPermissionEntity!]!
  }
  UsersPermissionsRole: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    description: string | null; // String
    name: string; // String!
    permissions: NexusGenRootTypes['UsersPermissionsPermissionRelationResponseCollection'] | null; // UsersPermissionsPermissionRelationResponseCollection
    type: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    users: NexusGenRootTypes['UsersPermissionsUserRelationResponseCollection'] | null; // UsersPermissionsUserRelationResponseCollection
  }
  UsersPermissionsRoleEntity: { // field return type
    attributes: NexusGenRootTypes['UsersPermissionsRole'] | null; // UsersPermissionsRole
    id: string | null; // ID
  }
  UsersPermissionsRoleEntityResponse: { // field return type
    data: NexusGenRootTypes['UsersPermissionsRoleEntity'] | null; // UsersPermissionsRoleEntity
  }
  UsersPermissionsRoleEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['UsersPermissionsRoleEntity'][]; // [UsersPermissionsRoleEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  UsersPermissionsRoleRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['UsersPermissionsRoleEntity'][]; // [UsersPermissionsRoleEntity!]!
  }
  UsersPermissionsUpdateRolePayload: { // field return type
    ok: boolean; // Boolean!
  }
  UsersPermissionsUser: { // field return type
    blocked: boolean | null; // Boolean
    confirmed: boolean | null; // Boolean
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    provider: string | null; // String
    role: NexusGenRootTypes['UsersPermissionsRoleEntityResponse'] | null; // UsersPermissionsRoleEntityResponse
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
    username: string; // String!
  }
  UsersPermissionsUserEntity: { // field return type
    attributes: NexusGenRootTypes['UsersPermissionsUser'] | null; // UsersPermissionsUser
    id: string | null; // ID
  }
  UsersPermissionsUserEntityResponse: { // field return type
    data: NexusGenRootTypes['UsersPermissionsUserEntity'] | null; // UsersPermissionsUserEntity
  }
  UsersPermissionsUserEntityResponseCollection: { // field return type
    data: NexusGenRootTypes['UsersPermissionsUserEntity'][]; // [UsersPermissionsUserEntity!]!
    meta: NexusGenRootTypes['ResponseCollectionMeta']; // ResponseCollectionMeta!
  }
  UsersPermissionsUserRelationResponseCollection: { // field return type
    data: NexusGenRootTypes['UsersPermissionsUserEntity'][]; // [UsersPermissionsUserEntity!]!
  }
}

export interface NexusGenFieldTypeNames {
  Cart: { // field return type name
    cart_items: 'CartItemRelationResponseCollection'
    createdAt: 'DateTime'
    publishedAt: 'DateTime'
    updatedAt: 'DateTime'
  }
  CartEntity: { // field return type name
    attributes: 'Cart'
    id: 'ID'
  }
  CartEntityResponse: { // field return type name
    data: 'CartEntity'
  }
  CartEntityResponseCollection: { // field return type name
    data: 'CartEntity'
    meta: 'ResponseCollectionMeta'
  }
  CartItem: { // field return type name
    cart: 'CartEntityResponse'
    createdAt: 'DateTime'
    product: 'ProductEntityResponse'
    publishedAt: 'DateTime'
    quantity: 'Int'
    updatedAt: 'DateTime'
  }
  CartItemEntity: { // field return type name
    attributes: 'CartItem'
    id: 'ID'
  }
  CartItemEntityResponse: { // field return type name
    data: 'CartItemEntity'
  }
  CartItemEntityResponseCollection: { // field return type name
    data: 'CartItemEntity'
    meta: 'ResponseCollectionMeta'
  }
  CartItemRelationResponseCollection: { // field return type name
    data: 'CartItemEntity'
  }
  CartRelationResponseCollection: { // field return type name
    data: 'CartEntity'
  }
  Category: { // field return type name
    createdAt: 'DateTime'
    description: 'String'
    name: 'String'
    products: 'ProductRelationResponseCollection'
    publishedAt: 'DateTime'
    slug: 'String'
    updatedAt: 'DateTime'
  }
  CategoryEntity: { // field return type name
    attributes: 'Category'
    id: 'ID'
  }
  CategoryEntityResponse: { // field return type name
    data: 'CategoryEntity'
  }
  CategoryEntityResponseCollection: { // field return type name
    data: 'CategoryEntity'
    meta: 'ResponseCollectionMeta'
  }
  CategoryRelationResponseCollection: { // field return type name
    data: 'CategoryEntity'
  }
  Collection: { // field return type name
    createdAt: 'DateTime'
    name: 'String'
    products: 'ProductRelationResponseCollection'
    publishedAt: 'DateTime'
    updatedAt: 'DateTime'
  }
  CollectionEntity: { // field return type name
    attributes: 'Collection'
    id: 'ID'
  }
  CollectionEntityResponse: { // field return type name
    data: 'CollectionEntity'
  }
  CollectionEntityResponseCollection: { // field return type name
    data: 'CollectionEntity'
    meta: 'ResponseCollectionMeta'
  }
  CollectionRelationResponseCollection: { // field return type name
    data: 'CollectionEntity'
  }
  Comment: { // field return type name
    content: 'String'
    createdAt: 'DateTime'
    email: 'String'
    headline: 'String'
    name: 'String'
    product: 'ProductEntityResponse'
    publishedAt: 'DateTime'
    rating: 'Int'
    updatedAt: 'DateTime'
  }
  CommentEntity: { // field return type name
    attributes: 'Comment'
    id: 'ID'
  }
  CommentEntityResponse: { // field return type name
    data: 'CommentEntity'
  }
  CommentEntityResponseCollection: { // field return type name
    data: 'CommentEntity'
    meta: 'ResponseCollectionMeta'
  }
  CommentRelationResponseCollection: { // field return type name
    data: 'CommentEntity'
  }
  Error: { // field return type name
    code: 'String'
    message: 'String'
  }
  I18NLocale: { // field return type name
    code: 'String'
    createdAt: 'DateTime'
    name: 'String'
    updatedAt: 'DateTime'
  }
  I18NLocaleEntity: { // field return type name
    attributes: 'I18NLocale'
    id: 'ID'
  }
  I18NLocaleEntityResponse: { // field return type name
    data: 'I18NLocaleEntity'
  }
  I18NLocaleEntityResponseCollection: { // field return type name
    data: 'I18NLocaleEntity'
    meta: 'ResponseCollectionMeta'
  }
  I18NLocaleRelationResponseCollection: { // field return type name
    data: 'I18NLocaleEntity'
  }
  Mutation: { // field return type name
    changePassword: 'UsersPermissionsLoginPayload'
    createCart: 'CartEntityResponse'
    createCartItem: 'CartItemEntityResponse'
    createCategory: 'CategoryEntityResponse'
    createCollection: 'CollectionEntityResponse'
    createComment: 'CommentEntityResponse'
    createProduct: 'ProductEntityResponse'
    createUploadFile: 'UploadFileEntityResponse'
    createUploadFolder: 'UploadFolderEntityResponse'
    createUsersPermissionsRole: 'UsersPermissionsCreateRolePayload'
    createUsersPermissionsUser: 'UsersPermissionsUserEntityResponse'
    deleteCart: 'CartEntityResponse'
    deleteCartItem: 'CartItemEntityResponse'
    deleteCategory: 'CategoryEntityResponse'
    deleteCollection: 'CollectionEntityResponse'
    deleteComment: 'CommentEntityResponse'
    deleteProduct: 'ProductEntityResponse'
    deleteUploadFile: 'UploadFileEntityResponse'
    deleteUploadFolder: 'UploadFolderEntityResponse'
    deleteUsersPermissionsRole: 'UsersPermissionsDeleteRolePayload'
    deleteUsersPermissionsUser: 'UsersPermissionsUserEntityResponse'
    emailConfirmation: 'UsersPermissionsLoginPayload'
    forgotPassword: 'UsersPermissionsPasswordPayload'
    login: 'UsersPermissionsLoginPayload'
    multipleUpload: 'UploadFileEntityResponse'
    register: 'UsersPermissionsLoginPayload'
    removeFile: 'UploadFileEntityResponse'
    resetPassword: 'UsersPermissionsLoginPayload'
    updateCart: 'CartEntityResponse'
    updateCartItem: 'CartItemEntityResponse'
    updateCategory: 'CategoryEntityResponse'
    updateCollection: 'CollectionEntityResponse'
    updateComment: 'CommentEntityResponse'
    updateFileInfo: 'UploadFileEntityResponse'
    updateProduct: 'ProductEntityResponse'
    updateUploadFile: 'UploadFileEntityResponse'
    updateUploadFolder: 'UploadFolderEntityResponse'
    updateUsersPermissionsRole: 'UsersPermissionsUpdateRolePayload'
    updateUsersPermissionsUser: 'UsersPermissionsUserEntityResponse'
    upload: 'UploadFileEntityResponse'
  }
  Pagination: { // field return type name
    page: 'Int'
    pageCount: 'Int'
    pageSize: 'Int'
    total: 'Int'
  }
  Product: { // field return type name
    avgRating: 'Int'
    cart_items: 'CartItemRelationResponseCollection'
    categories: 'CategoryRelationResponseCollection'
    collections: 'CollectionRelationResponseCollection'
    comments: 'CommentRelationResponseCollection'
    createdAt: 'DateTime'
    description: 'String'
    images: 'UploadFileRelationResponseCollection'
    name: 'String'
    price: 'Int'
    publishedAt: 'DateTime'
    ratingCount: 'Int'
    slug: 'String'
    updatedAt: 'DateTime'
  }
  ProductEntity: { // field return type name
    attributes: 'Product'
    id: 'ID'
  }
  ProductEntityResponse: { // field return type name
    data: 'ProductEntity'
  }
  ProductEntityResponseCollection: { // field return type name
    data: 'ProductEntity'
    meta: 'ResponseCollectionMeta'
  }
  ProductRelationResponseCollection: { // field return type name
    data: 'ProductEntity'
  }
  Query: { // field return type name
    cart: 'CartEntityResponse'
    cartItem: 'CartItemEntityResponse'
    cartItems: 'CartItemEntityResponseCollection'
    carts: 'CartEntityResponseCollection'
    categories: 'CategoryEntityResponseCollection'
    category: 'CategoryEntityResponse'
    collection: 'CollectionEntityResponse'
    collections: 'CollectionEntityResponseCollection'
    comment: 'CommentEntityResponse'
    comments: 'CommentEntityResponseCollection'
    i18NLocale: 'I18NLocaleEntityResponse'
    i18NLocales: 'I18NLocaleEntityResponseCollection'
    me: 'UsersPermissionsMe'
    product: 'ProductEntityResponse'
    products: 'ProductEntityResponseCollection'
    uploadFile: 'UploadFileEntityResponse'
    uploadFiles: 'UploadFileEntityResponseCollection'
    uploadFolder: 'UploadFolderEntityResponse'
    uploadFolders: 'UploadFolderEntityResponseCollection'
    usersPermissionsRole: 'UsersPermissionsRoleEntityResponse'
    usersPermissionsRoles: 'UsersPermissionsRoleEntityResponseCollection'
    usersPermissionsUser: 'UsersPermissionsUserEntityResponse'
    usersPermissionsUsers: 'UsersPermissionsUserEntityResponseCollection'
  }
  ResponseCollectionMeta: { // field return type name
    pagination: 'Pagination'
  }
  UploadFile: { // field return type name
    alternativeText: 'String'
    caption: 'String'
    createdAt: 'DateTime'
    ext: 'String'
    formats: 'JSON'
    hash: 'String'
    height: 'Int'
    mime: 'String'
    name: 'String'
    previewUrl: 'String'
    provider: 'String'
    provider_metadata: 'JSON'
    related: 'GenericMorph'
    size: 'Float'
    updatedAt: 'DateTime'
    url: 'String'
    width: 'Int'
  }
  UploadFileEntity: { // field return type name
    attributes: 'UploadFile'
    id: 'ID'
  }
  UploadFileEntityResponse: { // field return type name
    data: 'UploadFileEntity'
  }
  UploadFileEntityResponseCollection: { // field return type name
    data: 'UploadFileEntity'
    meta: 'ResponseCollectionMeta'
  }
  UploadFileRelationResponseCollection: { // field return type name
    data: 'UploadFileEntity'
  }
  UploadFolder: { // field return type name
    children: 'UploadFolderRelationResponseCollection'
    createdAt: 'DateTime'
    files: 'UploadFileRelationResponseCollection'
    name: 'String'
    parent: 'UploadFolderEntityResponse'
    path: 'String'
    pathId: 'Int'
    updatedAt: 'DateTime'
  }
  UploadFolderEntity: { // field return type name
    attributes: 'UploadFolder'
    id: 'ID'
  }
  UploadFolderEntityResponse: { // field return type name
    data: 'UploadFolderEntity'
  }
  UploadFolderEntityResponseCollection: { // field return type name
    data: 'UploadFolderEntity'
    meta: 'ResponseCollectionMeta'
  }
  UploadFolderRelationResponseCollection: { // field return type name
    data: 'UploadFolderEntity'
  }
  UsersPermissionsCreateRolePayload: { // field return type name
    ok: 'Boolean'
  }
  UsersPermissionsDeleteRolePayload: { // field return type name
    ok: 'Boolean'
  }
  UsersPermissionsLoginPayload: { // field return type name
    jwt: 'String'
    user: 'UsersPermissionsMe'
  }
  UsersPermissionsMe: { // field return type name
    blocked: 'Boolean'
    confirmed: 'Boolean'
    email: 'String'
    id: 'ID'
    role: 'UsersPermissionsMeRole'
    username: 'String'
  }
  UsersPermissionsMeRole: { // field return type name
    description: 'String'
    id: 'ID'
    name: 'String'
    type: 'String'
  }
  UsersPermissionsPasswordPayload: { // field return type name
    ok: 'Boolean'
  }
  UsersPermissionsPermission: { // field return type name
    action: 'String'
    createdAt: 'DateTime'
    role: 'UsersPermissionsRoleEntityResponse'
    updatedAt: 'DateTime'
  }
  UsersPermissionsPermissionEntity: { // field return type name
    attributes: 'UsersPermissionsPermission'
    id: 'ID'
  }
  UsersPermissionsPermissionEntityResponse: { // field return type name
    data: 'UsersPermissionsPermissionEntity'
  }
  UsersPermissionsPermissionEntityResponseCollection: { // field return type name
    data: 'UsersPermissionsPermissionEntity'
    meta: 'ResponseCollectionMeta'
  }
  UsersPermissionsPermissionRelationResponseCollection: { // field return type name
    data: 'UsersPermissionsPermissionEntity'
  }
  UsersPermissionsRole: { // field return type name
    createdAt: 'DateTime'
    description: 'String'
    name: 'String'
    permissions: 'UsersPermissionsPermissionRelationResponseCollection'
    type: 'String'
    updatedAt: 'DateTime'
    users: 'UsersPermissionsUserRelationResponseCollection'
  }
  UsersPermissionsRoleEntity: { // field return type name
    attributes: 'UsersPermissionsRole'
    id: 'ID'
  }
  UsersPermissionsRoleEntityResponse: { // field return type name
    data: 'UsersPermissionsRoleEntity'
  }
  UsersPermissionsRoleEntityResponseCollection: { // field return type name
    data: 'UsersPermissionsRoleEntity'
    meta: 'ResponseCollectionMeta'
  }
  UsersPermissionsRoleRelationResponseCollection: { // field return type name
    data: 'UsersPermissionsRoleEntity'
  }
  UsersPermissionsUpdateRolePayload: { // field return type name
    ok: 'Boolean'
  }
  UsersPermissionsUser: { // field return type name
    blocked: 'Boolean'
    confirmed: 'Boolean'
    createdAt: 'DateTime'
    email: 'String'
    provider: 'String'
    role: 'UsersPermissionsRoleEntityResponse'
    updatedAt: 'DateTime'
    username: 'String'
  }
  UsersPermissionsUserEntity: { // field return type name
    attributes: 'UsersPermissionsUser'
    id: 'ID'
  }
  UsersPermissionsUserEntityResponse: { // field return type name
    data: 'UsersPermissionsUserEntity'
  }
  UsersPermissionsUserEntityResponseCollection: { // field return type name
    data: 'UsersPermissionsUserEntity'
    meta: 'ResponseCollectionMeta'
  }
  UsersPermissionsUserRelationResponseCollection: { // field return type name
    data: 'UsersPermissionsUserEntity'
  }
}

export interface NexusGenArgTypes {
  Cart: {
    cart_items: { // args
      filters?: NexusGenInputs['CartItemFiltersInput'] | null; // CartItemFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
  }
  Category: {
    products: { // args
      filters?: NexusGenInputs['ProductFiltersInput'] | null; // ProductFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
  }
  Collection: {
    products: { // args
      filters?: NexusGenInputs['ProductFiltersInput'] | null; // ProductFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
  }
  Mutation: {
    changePassword: { // args
      currentPassword: string; // String!
      password: string; // String!
      passwordConfirmation: string; // String!
    }
    createCart: { // args
      data: NexusGenInputs['CartInput']; // CartInput!
    }
    createCartItem: { // args
      data: NexusGenInputs['CartItemInput']; // CartItemInput!
    }
    createCategory: { // args
      data: NexusGenInputs['CategoryInput']; // CategoryInput!
    }
    createCollection: { // args
      data: NexusGenInputs['CollectionInput']; // CollectionInput!
    }
    createComment: { // args
      data: NexusGenInputs['CommentInput']; // CommentInput!
    }
    createProduct: { // args
      data: NexusGenInputs['ProductInput']; // ProductInput!
    }
    createUploadFile: { // args
      data: NexusGenInputs['UploadFileInput']; // UploadFileInput!
    }
    createUploadFolder: { // args
      data: NexusGenInputs['UploadFolderInput']; // UploadFolderInput!
    }
    createUsersPermissionsRole: { // args
      data: NexusGenInputs['UsersPermissionsRoleInput']; // UsersPermissionsRoleInput!
    }
    createUsersPermissionsUser: { // args
      data: NexusGenInputs['UsersPermissionsUserInput']; // UsersPermissionsUserInput!
    }
    deleteCart: { // args
      id: string; // ID!
    }
    deleteCartItem: { // args
      id: string; // ID!
    }
    deleteCategory: { // args
      id: string; // ID!
    }
    deleteCollection: { // args
      id: string; // ID!
    }
    deleteComment: { // args
      id: string; // ID!
    }
    deleteProduct: { // args
      id: string; // ID!
    }
    deleteUploadFile: { // args
      id: string; // ID!
    }
    deleteUploadFolder: { // args
      id: string; // ID!
    }
    deleteUsersPermissionsRole: { // args
      id: string; // ID!
    }
    deleteUsersPermissionsUser: { // args
      id: string; // ID!
    }
    emailConfirmation: { // args
      confirmation: string; // String!
    }
    forgotPassword: { // args
      email: string; // String!
    }
    login: { // args
      input: NexusGenInputs['UsersPermissionsLoginInput']; // UsersPermissionsLoginInput!
    }
    multipleUpload: { // args
      field?: string | null; // String
      files: Array<NexusGenScalars['Upload'] | null>; // [Upload]!
      ref?: string | null; // String
      refId?: string | null; // ID
    }
    register: { // args
      input: NexusGenInputs['UsersPermissionsRegisterInput']; // UsersPermissionsRegisterInput!
    }
    removeFile: { // args
      id: string; // ID!
    }
    resetPassword: { // args
      code: string; // String!
      password: string; // String!
      passwordConfirmation: string; // String!
    }
    updateCart: { // args
      data: NexusGenInputs['CartInput']; // CartInput!
      id: string; // ID!
    }
    updateCartItem: { // args
      data: NexusGenInputs['CartItemInput']; // CartItemInput!
      id: string; // ID!
    }
    updateCategory: { // args
      data: NexusGenInputs['CategoryInput']; // CategoryInput!
      id: string; // ID!
    }
    updateCollection: { // args
      data: NexusGenInputs['CollectionInput']; // CollectionInput!
      id: string; // ID!
    }
    updateComment: { // args
      data: NexusGenInputs['CommentInput']; // CommentInput!
      id: string; // ID!
    }
    updateFileInfo: { // args
      id: string; // ID!
      info?: NexusGenInputs['FileInfoInput'] | null; // FileInfoInput
    }
    updateProduct: { // args
      data: NexusGenInputs['ProductInput']; // ProductInput!
      id: string; // ID!
    }
    updateUploadFile: { // args
      data: NexusGenInputs['UploadFileInput']; // UploadFileInput!
      id: string; // ID!
    }
    updateUploadFolder: { // args
      data: NexusGenInputs['UploadFolderInput']; // UploadFolderInput!
      id: string; // ID!
    }
    updateUsersPermissionsRole: { // args
      data: NexusGenInputs['UsersPermissionsRoleInput']; // UsersPermissionsRoleInput!
      id: string; // ID!
    }
    updateUsersPermissionsUser: { // args
      data: NexusGenInputs['UsersPermissionsUserInput']; // UsersPermissionsUserInput!
      id: string; // ID!
    }
    upload: { // args
      field?: string | null; // String
      file: NexusGenScalars['Upload']; // Upload!
      info?: NexusGenInputs['FileInfoInput'] | null; // FileInfoInput
      ref?: string | null; // String
      refId?: string | null; // ID
    }
  }
  Product: {
    cart_items: { // args
      filters?: NexusGenInputs['CartItemFiltersInput'] | null; // CartItemFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    categories: { // args
      filters?: NexusGenInputs['CategoryFiltersInput'] | null; // CategoryFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    collections: { // args
      filters?: NexusGenInputs['CollectionFiltersInput'] | null; // CollectionFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    comments: { // args
      filters?: NexusGenInputs['CommentFiltersInput'] | null; // CommentFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    images: { // args
      filters?: NexusGenInputs['UploadFileFiltersInput'] | null; // UploadFileFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
  }
  Query: {
    cart: { // args
      id?: string | null; // ID
    }
    cartItem: { // args
      id?: string | null; // ID
    }
    cartItems: { // args
      filters?: NexusGenInputs['CartItemFiltersInput'] | null; // CartItemFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    carts: { // args
      filters?: NexusGenInputs['CartFiltersInput'] | null; // CartFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    categories: { // args
      filters?: NexusGenInputs['CategoryFiltersInput'] | null; // CategoryFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    category: { // args
      id?: string | null; // ID
    }
    collection: { // args
      id?: string | null; // ID
    }
    collections: { // args
      filters?: NexusGenInputs['CollectionFiltersInput'] | null; // CollectionFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    comment: { // args
      id?: string | null; // ID
    }
    comments: { // args
      filters?: NexusGenInputs['CommentFiltersInput'] | null; // CommentFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    i18NLocale: { // args
      id?: string | null; // ID
    }
    i18NLocales: { // args
      filters?: NexusGenInputs['I18NLocaleFiltersInput'] | null; // I18NLocaleFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    product: { // args
      id?: string | null; // ID
    }
    products: { // args
      filters?: NexusGenInputs['ProductFiltersInput'] | null; // ProductFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      publicationState: NexusGenEnums['PublicationState'] | null; // PublicationState
      sort: Array<string | null> | null; // [String]
    }
    uploadFile: { // args
      id?: string | null; // ID
    }
    uploadFiles: { // args
      filters?: NexusGenInputs['UploadFileFiltersInput'] | null; // UploadFileFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    uploadFolder: { // args
      id?: string | null; // ID
    }
    uploadFolders: { // args
      filters?: NexusGenInputs['UploadFolderFiltersInput'] | null; // UploadFolderFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    usersPermissionsRole: { // args
      id?: string | null; // ID
    }
    usersPermissionsRoles: { // args
      filters?: NexusGenInputs['UsersPermissionsRoleFiltersInput'] | null; // UsersPermissionsRoleFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    usersPermissionsUser: { // args
      id?: string | null; // ID
    }
    usersPermissionsUsers: { // args
      filters?: NexusGenInputs['UsersPermissionsUserFiltersInput'] | null; // UsersPermissionsUserFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
  }
  UploadFolder: {
    children: { // args
      filters?: NexusGenInputs['UploadFolderFiltersInput'] | null; // UploadFolderFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    files: { // args
      filters?: NexusGenInputs['UploadFileFiltersInput'] | null; // UploadFileFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
  }
  UsersPermissionsRole: {
    permissions: { // args
      filters?: NexusGenInputs['UsersPermissionsPermissionFiltersInput'] | null; // UsersPermissionsPermissionFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
    users: { // args
      filters?: NexusGenInputs['UsersPermissionsUserFiltersInput'] | null; // UsersPermissionsUserFiltersInput
      pagination: NexusGenInputs['PaginationArg'] | null; // PaginationArg
      sort: Array<string | null> | null; // [String]
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  GenericMorph: "Cart" | "CartItem" | "Category" | "Collection" | "Comment" | "I18NLocale" | "Product" | "UploadFile" | "UploadFolder" | "UsersPermissionsPermission" | "UsersPermissionsRole" | "UsersPermissionsUser"
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = keyof NexusGenUnions;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = "GenericMorph";

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}